--02/01/2024
--@PLima
--RELATORIO 1507 - HSF - Indicadores Ordem de Servico

--banda setor:
--ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';
                    SELECT
                        4 AS ORDEM,
                        SAT.DS_SETOR_ATENDIMENTO AS LOCAL,
                        --LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) AS DATA,
                        EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE) AS ANO,
                        EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE) AS MES,
                        TO_CHAR(MOSA.DT_ATIVIDADE, 'Month') AS MES_TEXTO,
                        DECODE(ATP.IE_STATUS_ORDEM, 1, 'Aberta', 2, 'Processo', 3, IE_STATUS_ORDEM) AS STATUS,
                        COUNT(DISTINCT ATP.NR_SEQUENCIA) AS ORDEM_SERVICO_TOTAL,
                        SUM(MOSA.QT_MINUTO) AS MINUTOS_TOTAL,
                        LPAD(FLOOR((SUM(MOSA.QT_MINUTO) / 60) / COUNT(DISTINCT ATP.NR_SEQUENCIA)), 2, '0') AS HORA_HOMEM,
                        RPAD(MOD(ROUND(SUM(MOSA.QT_MINUTO) / COUNT(DISTINCT ATP.NR_SEQUENCIA)), 60), 2, '0') AS MINUTOS_HOMEM,
                        LPAD(FLOOR((SUM(MOSA.QT_MINUTO) / 60) / COUNT(DISTINCT ATP.NR_SEQUENCIA)), 2, '0') || ' horas e ' ||
                        RPAD(MOD(ROUND(SUM(MOSA.QT_MINUTO) / COUNT(DISTINCT ATP.NR_SEQUENCIA)), 60), 2, '0') || ' minutos' AS HORAS_MINUTOS_HOMEM
                    FROM    MAN_ORDEM_SERVICO ATP
                    INNER JOIN    MAN_GRUPO_TRABALHO SA ON SA.NR_SEQUENCIA = ATP.NR_GRUPO_TRABALHO
                    INNER JOIN    MAN_LOCALIZACAO ML ON ML.NR_SEQUENCIA = ATP.NR_SEQ_LOCALIZACAO
                    INNER JOIN    SETOR_ATENDIMENTO SAT ON SAT.CD_SETOR_ATENDIMENTO = ML.CD_SETOR
                    LEFT JOIN    MAN_GRUPO_PLANEJAMENTO MGP ON MGP.NR_SEQUENCIA = ATP.NR_GRUPO_PLANEJ
                    LEFT JOIN    MAN_ORDEM_SERV_ATIV MOSA ON MOSA.NR_SEQ_ORDEM_SERV = ATP.NR_SEQUENCIA
                    LEFT JOIN    MAN_TIPO_ORDEM_SERVICO MTOS ON MTOS.NR_SEQUENCIA = ATP.NR_SEQ_TIPO_ORDEM
                    --WHERE    TRUNC(MOSA.DT_ATIVIDADE) BETWEEN sysdate - 365 AND sysdate --:DT_INICIAL AND :DT_FINAL
                    --PROTECAO DE VALORES NULL
                    WHERE MOSA.DT_ATIVIDADE IS NOT NULL
                    and ATP.IE_STATUS_ORDEM = 1
                    GROUP BY
                        SAT.DS_SETOR_ATENDIMENTO,
                        LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)),
                        TO_CHAR(MOSA.DT_ATIVIDADE, 'Month'),
                        EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE),
                        EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE),
                        ATP.IE_STATUS_ORDEM
                    ORDER BY
                        SAT.DS_SETOR_ATENDIMENTO ASC,
                        EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE) DESC,
                        EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE) ASC
                    


--banda GERAL:
SELECT 
    1 AS ORDEM, 
    'HSF - GERAL' AS LOCAL,
    -- LAST_DAY(TRUNC(ATP.DT_ORDEM_SERVICO)) AS DATA,
    LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) AS DATA,
    COUNT(DISTINCT ATP.NR_SEQUENCIA) AS QUANTIDADE, SUM(MOSA.QT_MINUTO) AS MINUTOS,
    ROUND(SUM(MOSA.QT_MINUTO) / 60) AS HORAS
FROM	MAN_ORDEM_SERVICO ATP
INNER JOIN MAN_GRUPO_TRABALHO SA ON SA.NR_SEQUENCIA = ATP.NR_GRUPO_TRABALHO
INNER JOIN MAN_LOCALIZACAO ML ON ML.NR_SEQUENCIA = ATP.NR_SEQ_LOCALIZACAO
INNER JOIN SETOR_ATENDIMENTO SAT ON SAT.CD_SETOR_ATENDIMENTO = ML.CD_SETOR
LEFT JOIN MAN_GRUPO_PLANEJAMENTO MGP ON MGP.NR_SEQUENCIA = ATP.NR_GRUPO_PLANEJ
LEFT JOIN MAN_ORDEM_SERV_ATIV MOSA ON MOSA.NR_SEQ_ORDEM_SERV = ATP.NR_SEQUENCIA
LEFT JOIN MAN_TIPO_ORDEM_SERVICO MTOS ON MTOS.NR_SEQUENCIA = ATP.NR_SEQ_TIPO_ORDEM

--WHERE -- ATP.DT_ORDEM_SERVICO	BETWEEN :DT_INICIAL AND :DT_FINAL
WHERE TRUNC(MOSA.DT_ATIVIDADE) BETWEEN sysdate -365 and sysdate --:DT_INICIAL AND :DT_FINAL
--AND :VISAO_GERAL = 1
--@SQL_WHERE

GROUP BY  LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE))
ORDER BY LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) DESC





--=============================================================================================================================
--banda Geral / Tipo O.S.:
SELECT 
    5 AS ORDEM, 
    'HSF-GERAL-TIPO' AS LOCAL, 
    EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE) AS ANO,
    EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE) AS MES,
    TO_CHAR(MOSA.DT_ATIVIDADE, 'Month') AS MES_TEXTO,
    DECODE(ATP.IE_STATUS_ORDEM, 1, 'Aberta', 2, 'Processo', 3, 'Encerrada') AS STATUS,
    MTOS.DS_TIPO AS TIPO,
    COUNT(DISTINCT ATP.NR_SEQUENCIA) AS ORDEM_SERVICO_TOTAL,
    SUM(MOSA.QT_MINUTO) AS MINUTOS_TOTAL, 
    ROUND(SUM(MOSA.QT_MINUTO) / 60) AS HORAS_TOTAL,
    LPAD(FLOOR((SUM(MOSA.QT_MINUTO) / 60) / COUNT(DISTINCT ATP.NR_SEQUENCIA)), 2, '0') AS HORA_HOMEM,
    RPAD(MOD(ROUND(SUM(MOSA.QT_MINUTO) / COUNT(DISTINCT ATP.NR_SEQUENCIA)), 60), 2, '0') AS MINUTOS_HOMEM,
    LPAD(FLOOR((SUM(MOSA.QT_MINUTO) / 60) / COUNT(DISTINCT ATP.NR_SEQUENCIA)), 2, '0') || ' horas e ' ||
    RPAD(MOD(ROUND(SUM(MOSA.QT_MINUTO) / COUNT(DISTINCT ATP.NR_SEQUENCIA)), 60), 2, '0') || ' minutos' AS HORAS_MINUTOS_HOMEM,
    MGP.DS_GRUPO_PLANEJ AS GRUPO_PLANEJAMENTO
FROM	MAN_ORDEM_SERVICO ATP
LEFT JOIN MAN_GRUPO_TRABALHO SA ON SA.NR_SEQUENCIA = ATP.NR_GRUPO_TRABALHO
LEFT JOIN MAN_LOCALIZACAO ML ON ML.NR_SEQUENCIA = ATP.NR_SEQ_LOCALIZACAO
LEFT JOIN SETOR_ATENDIMENTO SAT ON SAT.CD_SETOR_ATENDIMENTO = ML.CD_SETOR
LEFT JOIN MAN_GRUPO_PLANEJAMENTO MGP ON MGP.NR_SEQUENCIA = ATP.NR_GRUPO_PLANEJ
LEFT JOIN MAN_ORDEM_SERV_ATIV MOSA ON MOSA.NR_SEQ_ORDEM_SERV = ATP.NR_SEQUENCIA
LEFT JOIN MAN_TIPO_ORDEM_SERVICO MTOS ON MTOS.NR_SEQUENCIA = ATP.NR_SEQ_TIPO_ORDEM
WHERE MOSA.DT_ATIVIDADE IS NOT NULL
AND MGP.NR_SEQUENCIA = 22 --GRUPO_PLANEJ
AND ATP.DT_ORDEM_SERVICO BETWEEN SYSDATE - 8 AND SYSDATE
--AND ATP.IE_STATUS_ORDEM = 1

GROUP BY  MOSA.DT_ATIVIDADE, ATP.IE_STATUS_ORDEM, MTOS.DS_TIPO, MGP.DS_GRUPO_PLANEJ
ORDER BY 
    EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE) DESC,
    EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE) DESC,
    MTOS.DS_TIPO ASC




--banda Geral / Tipo O.S. ANALITICO:
SELECT 
    ATP.NR_SEQUENCIA AS ORDEM_SERVICO,
    EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE) AS ANO,
    EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE) AS MES,
    EXTRACT(DAY FROM MOSA.DT_ATIVIDADE) AS DIA,
    TO_CHAR(MOSA.DT_ATIVIDADE, 'Month') AS MES_TEXTO,
    MTOS.DS_TIPO AS TIPO,
    DECODE(ATP.IE_STATUS_ORDEM, 1, 'Aberta', 2, 'Processo', 3, ATP.IE_STATUS_ORDEM) AS STATUS,
    DECODE(ATP.IE_PRIORIDADE, 'A', 'Alta', 'M', 'Média', 'E','Emergência', 'Fora da Prioridade') AS DS_PRIORIDADE, 
    ABREVIA_NOME( INITCAP(OBTER_NOME_USUARIO(MOSA.NM_USUARIO_EXEC)),'A') AS ANALISTA,
    MOSA.QT_MINUTO AS MINUTOS_TOTAL,
    MGP.DS_GRUPO_PLANEJ AS GRUPO_PLANEJAMENTO
FROM	MAN_ORDEM_SERVICO ATP
LEFT JOIN MAN_GRUPO_TRABALHO SA ON SA.NR_SEQUENCIA = ATP.NR_GRUPO_TRABALHO
LEFT JOIN MAN_LOCALIZACAO ML ON ML.NR_SEQUENCIA = ATP.NR_SEQ_LOCALIZACAO
LEFT JOIN SETOR_ATENDIMENTO SAT ON SAT.CD_SETOR_ATENDIMENTO = ML.CD_SETOR
LEFT JOIN MAN_GRUPO_PLANEJAMENTO MGP ON MGP.NR_SEQUENCIA = ATP.NR_GRUPO_PLANEJ
LEFT JOIN MAN_ORDEM_SERV_ATIV MOSA ON MOSA.NR_SEQ_ORDEM_SERV = ATP.NR_SEQUENCIA
LEFT JOIN MAN_TIPO_ORDEM_SERVICO MTOS ON MTOS.NR_SEQUENCIA = ATP.NR_SEQ_TIPO_ORDEM
--WHERE MOSA.DT_ATIVIDADE IS NOT NULL
--AND MGP.NR_SEQUENCIA = 22 
--AND ATP.DT_ORDEM_SERVICO BETWEEN SYSDATE - 8 AND SYSDATE
WHERE ATP.NR_SEQUENCIA = 158930

ORDER BY 
    EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE) DESC,
    EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE) DESC,
    EXTRACT(DAY FROM MOSA.DT_ATIVIDADE),
    MTOS.DS_TIPO , MTOS.DS_TIPO

--=============================================================================================================================



--banda Grupo de Trabalho:
SELECT 
    2 AS ORDEM, 
    SA.DS_GRUPO_TRABALHO AS LOCAL,
    -- LAST_DAY(TRUNC(ATP.DT_ORDEM_SERVICO)) AS DATA,
    LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) AS DATA,
    COUNT(DISTINCT ATP.NR_SEQUENCIA) AS QUANTIDADE, 
    SUM(MOSA.QT_MINUTO) AS MINUTOS,
    ROUND(SUM(MOSA.QT_MINUTO) / 60) AS HORAS
FROM	MAN_ORDEM_SERVICO ATP
INNER JOIN MAN_GRUPO_TRABALHO SA ON SA.NR_SEQUENCIA = ATP.NR_GRUPO_TRABALHO
INNER JOIN MAN_LOCALIZACAO ML ON ML.NR_SEQUENCIA = ATP.NR_SEQ_LOCALIZACAO
INNER JOIN SETOR_ATENDIMENTO SAT ON SAT.CD_SETOR_ATENDIMENTO = ML.CD_SETOR
LEFT JOIN MAN_GRUPO_PLANEJAMENTO MGP ON MGP.NR_SEQUENCIA = ATP.NR_GRUPO_PLANEJ
LEFT JOIN MAN_ORDEM_SERV_ATIV MOSA ON MOSA.NR_SEQ_ORDEM_SERV = ATP.NR_SEQUENCIA
LEFT JOIN MAN_TIPO_ORDEM_SERVICO MTOS ON MTOS.NR_SEQUENCIA = ATP.NR_SEQ_TIPO_ORDEM
WHERE
TRUNC(MOSA.DT_ATIVIDADE) BETWEEN sysdate -365 and sysdate --:DT_INICIAL AND :DT_FINAL
--AND :VISAO_GRUPO_TRABALHO = 2
--@SQL_WHERE
GROUP BY  SA.DS_GRUPO_TRABALHO, LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE))
ORDER BY SA.DS_GRUPO_TRABALHO ASC, LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) DESC


--banda Grupo de Trabalho / Status O.S:
SELECT 
    3 AS ORDEM, 
    SA.DS_GRUPO_TRABALHO AS LOCAL,
    -- LAST_DAY(TRUNC(ATP.DT_ORDEM_SERVICO)) AS DATA,
    LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) AS DATA,
    DECODE(ATP.IE_STATUS_ORDEM, 1, 'Aberta', 2, 'Processo', 3, 'Encerrada') AS STATUS, 
    COUNT(DISTINCT ATP.NR_SEQUENCIA) AS QUANTIDADE,
    SUM(MOSA.QT_MINUTO) AS MINUTOS, 
    ROUND(SUM(MOSA.QT_MINUTO) / 60) AS HORAS
FROM	MAN_ORDEM_SERVICO ATP
INNER JOIN MAN_GRUPO_TRABALHO SA ON SA.NR_SEQUENCIA = ATP.NR_GRUPO_TRABALHO
INNER JOIN MAN_LOCALIZACAO ML ON ML.NR_SEQUENCIA = ATP.NR_SEQ_LOCALIZACAO
INNER JOIN SETOR_ATENDIMENTO SAT ON SAT.CD_SETOR_ATENDIMENTO = ML.CD_SETOR
LEFT JOIN MAN_GRUPO_PLANEJAMENTO MGP ON MGP.NR_SEQUENCIA = ATP.NR_GRUPO_PLANEJ
LEFT JOIN MAN_ORDEM_SERV_ATIV MOSA ON MOSA.NR_SEQ_ORDEM_SERV = ATP.NR_SEQUENCIA
LEFT JOIN MAN_TIPO_ORDEM_SERVICO MTOS ON MTOS.NR_SEQUENCIA = ATP.NR_SEQ_TIPO_ORDEM
WHERE
-- ATP.DT_ORDEM_SERVICO	BETWEEN :DT_INICIAL AND :DT_FINAL
TRUNC(MOSA.DT_ATIVIDADE) BETWEEN sysdate -365 and sysdate --:DT_INICIAL AND :DT_FINAL
--AND :VISAO_GRUPO_TRAB_STATUS_OS = 3
--@SQL_WHERE
GROUP BY 
    SA.DS_GRUPO_TRABALHO, 
    LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)), 
    ATP.IE_STATUS_ORDEM
ORDER BY 
    SA.DS_GRUPO_TRABALHO ASC, 
    LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) DESC, 
    ATP.IE_STATUS_ORDEM ASC


--banda Executor da Atividade da O.S.:
ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';
SELECT 
    6 AS ORDEM, 
    INITCAP(OBTER_NOME_USUARIO(MOSA.NM_USUARIO_EXEC)) AS LOCAL, 
    EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE) AS ANO,
    EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE) AS MES,
    TO_CHAR(MOSA.DT_ATIVIDADE, 'Month') AS MES_TEXTO,
    SUM(MOSA.QT_MINUTO) AS MINUTOS_TOTAL, 
    ROUND(SUM(MOSA.QT_MINUTO) / 60) AS HORAS
FROM	MAN_ORDEM_SERVICO ATP
INNER JOIN MAN_GRUPO_TRABALHO SA ON SA.NR_SEQUENCIA = ATP.NR_GRUPO_TRABALHO
INNER JOIN MAN_LOCALIZACAO ML ON ML.NR_SEQUENCIA = ATP.NR_SEQ_LOCALIZACAO
INNER JOIN SETOR_ATENDIMENTO SAT ON SAT.CD_SETOR_ATENDIMENTO = ML.CD_SETOR
LEFT JOIN MAN_GRUPO_PLANEJAMENTO MGP ON MGP.NR_SEQUENCIA = ATP.NR_GRUPO_PLANEJ
LEFT JOIN MAN_ORDEM_SERV_ATIV MOSA ON MOSA.NR_SEQ_ORDEM_SERV = ATP.NR_SEQUENCIA
LEFT JOIN MAN_TIPO_ORDEM_SERVICO MTOS ON MTOS.NR_SEQUENCIA = ATP.NR_SEQ_TIPO_ORDEM
--PROTECAO DE VALORES NULL
WHERE MOSA.DT_ATIVIDADE IS NOT NULL
GROUP BY 
    LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)), 
    OBTER_NOME_USUARIO(MOSA.NM_USUARIO_EXEC),
    TO_CHAR(MOSA.DT_ATIVIDADE, 'Month'),
    EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE),
    EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE)
ORDER BY 
    OBTER_NOME_USUARIO(MOSA.NM_USUARIO_EXEC) ASC, 
    EXTRACT(YEAR FROM MOSA.DT_ATIVIDADE) DESC,
    EXTRACT(MONTH FROM MOSA.DT_ATIVIDADE) ASC;
