--HSF - Indicadores Ordem de Serviço

--GERAL:
SELECT 
1 AS ORDEM, 'HSF - GERAL' AS LOCAL,
-- LAST_DAY(TRUNC(ATP.DT_ORDEM_SERVICO)) AS DATA,
 LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) AS DATA,
COUNT(DISTINCT ATP.NR_SEQUENCIA) AS QUANTIDADE, SUM(MOSA.QT_MINUTO) AS MINUTOS,
ROUND(SUM(MOSA.QT_MINUTO) / 60) AS HORAS
FROM	MAN_ORDEM_SERVICO ATP
INNER JOIN MAN_GRUPO_TRABALHO SA ON SA.NR_SEQUENCIA = ATP.NR_GRUPO_TRABALHO
INNER JOIN MAN_LOCALIZACAO ML ON ML.NR_SEQUENCIA = ATP.NR_SEQ_LOCALIZACAO
INNER JOIN SETOR_ATENDIMENTO SAT ON SAT.CD_SETOR_ATENDIMENTO = ML.CD_SETOR
LEFT JOIN MAN_GRUPO_PLANEJAMENTO MGP ON MGP.NR_SEQUENCIA = ATP.NR_GRUPO_PLANEJ
LEFT JOIN MAN_ORDEM_SERV_ATIV MOSA ON MOSA.NR_SEQ_ORDEM_SERV = ATP.NR_SEQUENCIA
LEFT JOIN MAN_TIPO_ORDEM_SERVICO MTOS ON MTOS.NR_SEQUENCIA = ATP.NR_SEQ_TIPO_ORDEM
WHERE
-- ATP.DT_ORDEM_SERVICO	BETWEEN :DT_INICIAL AND :DT_FINAL
TRUNC(MOSA.DT_ATIVIDADE)	BETWEEN :DT_INICIAL AND :DT_FINAL
AND :VISAO_GERAL = 1
@SQL_WHERE
-- GROUP BY LAST_DAY(TRUNC(ATP.DT_ORDEM_SERVICO))
-- ORDER BY LAST_DAY(TRUNC(ATP.DT_ORDEM_SERVICO)) DESC
GROUP BY  LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE))
ORDER BY LAST_DAY(TRUNC(MOSA.DT_ATIVIDADE)) DESC